2023-05-30 23:29:20,292 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:29:20,292 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:29:20,292 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:29:20,292 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:29:20,293 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:29:20,293 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:29:20,371 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:29:20,373 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_232920-hc0dz9jb\logs\debug.log
2023-05-30 23:29:20,374 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_232920-hc0dz9jb\logs\debug-internal.log
2023-05-30 23:29:20,375 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:29:20,375 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:29:20,376 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:29:20,376 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:29:20,393 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:29:20,402 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:29:20,409 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:29:20,409 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:29:20,409 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:29:20,461 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:30:20,996 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:30:21,088 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:32:19,392 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:32:19,393 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:32:19,393 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:32:19,394 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:32:19,394 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:32:19,394 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:32:19,405 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:32:19,405 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233219-g52t5s11\logs\debug.log
2023-05-30 23:32:19,405 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233219-g52t5s11\logs\debug-internal.log
2023-05-30 23:32:19,406 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:32:19,406 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:32:19,406 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:32:19,406 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:32:19,413 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:32:19,419 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:32:19,424 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:32:19,424 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:32:19,424 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:32:19,485 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:33:20,128 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:33:20,224 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:33:40,020 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:33:40,020 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:33:40,021 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:33:40,021 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:33:40,021 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:33:40,021 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:33:41,312 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:33:41,313 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233340-bz1ee8os\logs\debug.log
2023-05-30 23:33:41,314 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233340-bz1ee8os\logs\debug-internal.log
2023-05-30 23:33:41,315 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:33:41,316 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:33:41,317 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:33:41,318 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:33:41,330 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:33:41,337 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:33:41,343 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:33:41,344 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:33:41,344 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:33:41,395 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:34:41,950 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:34:42,047 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:35:10,559 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:35:10,559 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:35:10,560 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:35:10,560 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:35:10,560 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:35:10,560 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:35:10,578 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:35:10,579 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233510-t729yl4y\logs\debug.log
2023-05-30 23:35:10,580 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233510-t729yl4y\logs\debug-internal.log
2023-05-30 23:35:10,580 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:35:10,581 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:35:10,581 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:35:10,581 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:35:10,586 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:35:10,592 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:35:10,597 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:35:10,598 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:35:10,598 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:35:10,648 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:35:43,941 WARNING MainThread:13720 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 740, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2023-05-30 23:36:15,591 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:36:15,591 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:36:15,591 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:36:15,592 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:36:15,592 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:36:15,592 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:36:15,981 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:36:15,982 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233615-7222qhtl\logs\debug.log
2023-05-30 23:36:15,983 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_233615-7222qhtl\logs\debug-internal.log
2023-05-30 23:36:15,983 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:36:15,984 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:36:15,984 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:36:15,985 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:36:15,996 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:36:16,005 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:36:16,010 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:36:16,011 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:36:16,011 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:36:16,061 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:37:16,645 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:37:16,894 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:40:37,350 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:40:37,351 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:40:37,351 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:40:37,352 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:40:37,352 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:40:37,352 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:40:37,416 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:40:37,416 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234037-66o4vv06\logs\debug.log
2023-05-30 23:40:37,417 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234037-66o4vv06\logs\debug-internal.log
2023-05-30 23:40:37,417 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:40:37,417 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'max_depth': 10, 'random_state': 0}
2023-05-30 23:40:37,418 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:40:37,418 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:40:37,424 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:40:37,429 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:40:37,434 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:40:37,435 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:40:37,435 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:40:37,486 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:41:38,007 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:41:38,108 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:44:01,837 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:44:01,838 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:44:01,838 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:44:01,839 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:44:01,839 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:44:01,839 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:44:02,003 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:44:02,007 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234401-d9uig2ux\logs\debug.log
2023-05-30 23:44:02,009 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234401-d9uig2ux\logs\debug-internal.log
2023-05-30 23:44:02,010 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:44:02,012 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:44:02,013 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:44:02,014 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:44:02,026 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:44:02,035 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:44:02,040 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:44:02,041 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:44:02,041 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:44:02,090 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:45:02,700 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:45:02,791 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:46:09,195 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-05-30 23:46:09,196 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Configure stats pid to 13720
2023-05-30 23:46:09,196 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from C:\Users\user\.config\wandb\settings
2023-05-30 23:46:09,196 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from E:\MLOPS\MLOPS\homework-wandb\wandb\settings
2023-05-30 23:46:09,197 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-30 23:46:09,197 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-30 23:46:09,216 INFO    MainThread:13720 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-30 23:46:09,216 INFO    MainThread:13720 [wandb_init.py:_log_setup():507] Logging user logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234609-rwdoxni8\logs\debug.log
2023-05-30 23:46:09,217 INFO    MainThread:13720 [wandb_init.py:_log_setup():508] Logging internal logs to E:\MLOPS\MLOPS\homework-wandb\wandb\run-20230530_234609-rwdoxni8\logs\debug-internal.log
2023-05-30 23:46:09,217 INFO    MainThread:13720 [wandb_init.py:init():547] calling init triggers
2023-05-30 23:46:09,217 INFO    MainThread:13720 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-05-30 23:46:09,217 INFO    MainThread:13720 [wandb_init.py:init():596] starting backend
2023-05-30 23:46:09,218 INFO    MainThread:13720 [wandb_init.py:init():600] setting up manager
2023-05-30 23:46:09,223 INFO    MainThread:13720 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-30 23:46:09,229 INFO    MainThread:13720 [wandb_init.py:init():606] backend started and connected
2023-05-30 23:46:09,233 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-30 23:46:09,233 INFO    MainThread:13720 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-30 23:46:09,234 INFO    MainThread:13720 [wandb_init.py:init():700] updated telemetry
2023-05-30 23:46:09,334 INFO    MainThread:13720 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-30 23:47:09,900 ERROR   MainThread:13720 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:47:10,004 ERROR   MainThread:13720 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-05-30 23:47:31,501 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,502 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,502 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,502 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,503 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,503 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,503 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,504 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,504 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,504 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,504 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
2023-05-30 23:47:31,537 WARNING MsgRouterThr:13720 [router.py:message_loop():77] message_loop has been closed
